## LAB ACTIVITY 13
## NAME : SONALI R; REG NO : 22MID0061; COURSE CODE: CSI3007; LAB : L27+L28;
## DATE : 12/09/2025

# 2. Handling EXCEL

## Read from an EXCEL file

In [7]:
import pandas as pd

#Read the Excel file into a DataFrame
df = pd.read_excel('Orders.xlsx', sheet_name = "Orders") #Use the read_excel() function to import your data.

In [8]:
print(df.head()) # Displays first 5 rows

   Row ID        Order ID Order Date  Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520   
1       2  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520   
2       3  CA-2016-138688 2016-06-12 2016-06-16    Second Class    DV-13045   
3       4  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335   
4       5  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335   

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...   
1      Claire Gute   Consumer  United States        Henderson  ...   
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...   
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10

In [9]:
print(df.describe()) # Displays the statistics

            Row ID                     Order Date  \
count  9994.000000                           9994   
mean   4997.500000  2016-04-30 00:07:12.259355648   
min       1.000000            2014-01-03 00:00:00   
25%    2499.250000            2015-05-23 00:00:00   
50%    4997.500000            2016-06-26 00:00:00   
75%    7495.750000            2017-05-14 00:00:00   
max    9994.000000            2017-12-30 00:00:00   
std    2885.163629                            NaN   

                           Ship Date   Postal Code         Sales     Quantity  \
count                           9994   9994.000000   9994.000000  9994.000000   
mean   2016-05-03 23:06:58.571142912  55190.379428    229.858001     3.789574   
min              2014-01-07 00:00:00   1040.000000      0.444000     1.000000   
25%              2015-05-27 00:00:00  23223.000000     17.280000     2.000000   
50%              2016-06-29 00:00:00  56430.500000     54.490000     3.000000   
75%              2017-05-18 00:00:00

In [10]:
print(df.shape) # Displays the row and column

(9994, 21)


In [12]:
print(df.info()) # Statistical Information about Excel file

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   Row ID         9994 non-null   int64         
 1   Order ID       9994 non-null   object        
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object        
 5   Customer ID    9994 non-null   object        
 6   Customer Name  9994 non-null   object        
 7   Segment        9994 non-null   object        
 8   Country        9994 non-null   object        
 9   City           9994 non-null   object        
 10  State          9994 non-null   object        
 11  Postal Code    9994 non-null   int64         
 12  Region         9994 non-null   object        
 13  Product ID     9994 non-null   object        
 14  Category       9994 non-null   object        
 15  Sub-Category   9994 n

## Extract the contents

In [14]:
# Extracting high-profit orders in a specific region
high_profit_west_df = df[(df['Region'] == 'West') & (df['Profit'] > 500)]
print(high_profit_west_df)

      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
251      252  CA-2016-145625 2016-09-11 2016-09-17  Standard Class   
392      393  US-2014-135972 2014-09-21 2014-09-23    Second Class   
515      516  CA-2017-127432 2017-01-22 2017-01-27  Standard Class   
814      815  CA-2017-143686 2017-05-14 2017-05-14        Same Day   
1625    1626  CA-2015-157084 2015-12-19 2015-12-24  Standard Class   
1644    1645  CA-2015-111829 2015-03-19 2015-03-20     First Class   
1711    1712  CA-2017-123491 2017-10-30 2017-11-05  Standard Class   
3273    3274  CA-2017-133865 2017-05-08 2017-05-12  Standard Class   
3570    3571  CA-2017-168109 2017-07-03 2017-07-03        Same Day   
3628    3629  CA-2014-169726 2014-08-09 2014-08-13  Standard Class   
3983    3984  CA-2016-135265 2016-07-07 2016-07-09    Second Class   
4619    4620  CA-2017-145219 2017-12-24 2017-12-25     First Class   
5425    5426  CA-2016-153598 2016-12-03 2016-12-06     First Class   
5990    5991  US-201

## Write the output of a Query into an EXCEL File

In [20]:
# Write the query results to a new Excel file
output_file = 'high_profit_west_region.xlsx'
high_profit_west_df.to_excel(output_file, index=False)

In [21]:
data = pd.read_excel('high_profit_west_region.xlsx')

In [22]:
# Display the first 5 rows of Output file extracted from the query
print(data.head())

   Row ID        Order ID Order Date  Ship Date       Ship Mode Customer ID  \
0     252  CA-2016-145625 2016-09-11 2016-09-17  Standard Class    KC-16540   
1     393  US-2014-135972 2014-09-21 2014-09-23    Second Class    JG-15115   
2     516  CA-2017-127432 2017-01-22 2017-01-27  Standard Class    AD-10180   
3     815  CA-2017-143686 2017-05-14 2017-05-14        Same Day    PJ-19015   
4    1626  CA-2015-157084 2015-12-19 2015-12-24  Standard Class    JG-15160   

     Customer Name      Segment        Country         City  ... Postal Code  \
0  Kelly Collister     Consumer  United States    San Diego  ...       92037   
1       Jack Garza     Consumer  United States   Des Moines  ...       98198   
2   Alan Dominguez  Home Office  United States  Great Falls  ...       59405   
3  Pauline Johnson     Consumer  United States    Santa Ana  ...       92704   
4     James Galang     Consumer  United States  Los Angeles  ...       90049   

   Region       Product ID    Category Sub-C

## Append to an Excel file

In [25]:
# Create a small DataFrame with new order data to append
new_order_data = {'Row ID': [9995], 'Order ID': ['CA-2025-123456'], 'Order Date': ['2025-09-12'],
                  'Ship Date': ['2025-09-16'], 'Ship Mode': ['Standard Class'], 'Customer ID': ['CH-12070'],
                  'Customer Name': ['Chris H'], 'Segment': ['Consumer'], 'Country': ['United States'],
                  'City': ['Los Angeles'], 'State': ['California'], 'Postal Code': [90001],
                  'Region': ['West'], 'Product ID': ['OFF-LA-10000001'], 'Category': ['Office Supplies'],
                  'Sub-Category': ['Labels'], 'Product Name': ['Colored Labels'], 'Sales': [15.50],
                  'Quantity': [1], 'Discount': [0.0], 'Profit': [7.05]}
new_orders_df = pd.DataFrame(new_order_data)

In [62]:
import pandas as pd
import os

# Define the file path
file_path = 'Orders.xlsx'

# Create a small DataFrame with new order data to append
# Ensure the column names and data types match your existing file
new_order_data = {'Row ID': [1], 'Order ID': ['US-2025-987654'], 'Order Date': ['2025-09-12'],
                  'Ship Date': ['2025-09-16'], 'Ship Mode': ['Standard Class'], 'Customer ID': ['ZZ-99999'],
                  'Customer Name': ['Zoe Z'], 'Segment': ['Consumer'], 'Country': ['United States'],
                  'City': ['Seattle'], 'State': ['Washington'], 'Postal Code': [98101],
                  'Region': ['West'], 'Product ID': ['OFF-PA-10000123'], 'Category': ['Office Supplies'],
                  'Sub-Category': ['Paper'], 'Product Name': ['Premium Copy Paper'], 'Sales': [25.00],
                  'Quantity': [2], 'Discount': [0.0], 'Profit': [10.00]}
new_orders_df = pd.DataFrame(new_order_data)

# --- Simple Append Logic ---
try:
    # Check if the file exists and has data
    if os.path.exists(file_path) and os.path.getsize(file_path) > 0:
        # 1. Read the entire existing Excel file into a DataFrame
        existing_df = pd.read_excel(file_path)

        # 2. Concatenate the existing DataFrame and the new DataFrame
        combined_df = pd.concat([existing_df, new_orders_df], ignore_index=True)

        # 3. Write the combined DataFrame back to the same Excel file, overwriting it
        combined_df.to_excel(file_path, index=False)
        
        print(f"Successfully appended new data and updated '{file_path}'.")
    else:
        # If the file does not exist or is empty, just save the new data
        new_orders_df.to_excel(file_path, index=False)
        print(f"Created a new file '{file_path}' and wrote the new data.")

except Exception as e:
    print(f"An error occurred: {e}")


An error occurred: File is not a zip file


# 4. Creating Numpy Arrays

In [29]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]]) # Creating a 2-D Array
print(arr) 

[[1 2 3]
 [4 5 6]]


In [30]:
print(arr.size) # Displays the number of elements in a array

6


In [31]:
print(arr.shape) # Display the rows and columns

(2, 3)


In [32]:
print(arr.ndim) # Displays the dimension of array

2


In [33]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])
print("Original array:", arr)
print("Original shape:", arr.shape)

Original array: [1 2 3 4 5 6]
Original shape: (6,)


In [35]:
# Reshape to a 2D array (2 rows, 3 columns)
reshaped_arr = arr.reshape(2, 3) # Reshape a 1-D array to 2-D array
print(reshaped_arr)
print("New shape:", reshaped_arr.shape)

[[1 2 3]
 [4 5 6]]
New shape: (2, 3)


In [37]:
import numpy as np
def numpysum(n):
  a = np.arange(n) ** 2  #Creates an array [0,1,..n-1] and element-wise sqauring
  b = np.arange(n) ** 3
  c = a + b #element wise adding - NO LOOP Overhead, hence Memory Efficient
  return c

numpysum(10) # function call

array([  0,   2,  12,  36,  80, 150, 252, 392, 576, 810])

In [38]:
#Creating Arrays from Sequences
#a list of numbers will create a 1D array,
a1D = np.array([1, 2, 3, 4])
print(a1D)

[1 2 3 4]


In [39]:
#a list of lists will create a 2D array
a2D = np.array([[1, 2], [3, 4]])
print(a2D)

[[1 2]
 [3 4]]


In [40]:
#further nested lists will create higher-dimensional arrays. 
#In general, any array object is called an ndarray in NumPy.
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a3D)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [41]:
import numpy as np
np.array([127, 128, 129], dtype=np.int32) 

array([127, 128, 129], dtype=int32)

| Name       | Alias(es)       | Size   | Range                           |
| ---------- | --------------- | ------ | ------------------------------- |
| `np.int8`  | `int8`          | 8-bit  | −128 to 127                     |
| `np.int16` | `int16`         | 16-bit | −32,768 to 32,767               |
| `np.int32` | `int32`, `int_` | 32-bit | −2,147,483,648 to 2,147,483,647 |
| `np.int64` | `int64`         | 64-bit | −9.2e18 to 9.2e18 (approx.)     |


In [43]:
import numpy as np
np.array([127, 128, 129], dtype=np.int8)
# Error: OverflowError because the np.int8 data type cannot hold the values 128 and 129. 

/tmp/ipykernel_77742/720755805.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  np.array([127, 128, 129], dtype=np.int8)
/tmp/ipykernel_77742/720755805.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  np.array([127, 128, 129], dtype=np.int8)


array([ 127, -128, -127], dtype=int8)

In [44]:
#ARRAY CREATION FUNCTIONS
import numpy as np
np.arange(10) #0 TO BEFORE 10, Step Value 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(2, 10, dtype=float) #2. to Before 10., step value 1.

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [46]:
np.arange(2, 3, 0.1) #2 to Before 3, step value 0.1.

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [47]:
#numpy.linspace will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values. 
#For example:

# np.linspace(start, stop, num)

# Start: 1.0

# Stop: 4.0

# num: 6 (number of samples including both endpoints)

# The interval is divided into 5 equal steps (because 6 points mean 5 intervals).
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [48]:
#2D Array Creation functions 
#properties of special matrices represented as 2D arrays.
np.eye(3) # Identity matrice of 3X3


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
np.eye(3, 5)   # Identity matrice of 3X

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [55]:
np.eye(3, 5, k=-2) #optional k argument
# When k is negative (e.g., k=-2), the diagonal shifts below the main diagonal
# when k is positive (e.g., k=1), the diagonal shifts above the main diagonal. 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [56]:
np.eye(3, 5, k=2) # Positive k argument

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
# numpy.diag can define either a square 2D array with given values along the diagonal or if given a 2D array 
# returns a 1D array that is only the diagonal elements. 
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [60]:
# np.diag(v, k=1):
# When v is a 1D array, np.diag creates a 2D square matrix with v placed along the k-th diagonal.
# k=1 → the diagonal above the main (first superdiagonal).
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [61]:
# To hold this upper diagonal, NumPy creates a (n + k) × (n + k) square matrix, where n is the length of the input array.
# So for [1, 2, 3]: Length = 3, k = 1, Matrix shape = 4 × 4
# Diagonal values are placed at positions: (0,1), (1,2), (2,3)
a = np.array([[1, 2], [3, 4]])
np.diag(a)

array([1, 4])